# Generated by Django 4.0 on 2021-12-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userprofile_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_img',
            field=models.ImageField(blank=True, default='img/default_avatar.png', upload_to='img/users'),
        ),
    ]
