# Generated by Django 4.0 on 2021-12-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_account_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_img',
            field=models.ImageField(blank=True, default='default_avatar.png', upload_to='img/users'),
        ),
    ]
