# Generated by Django 4.0 on 2022-01-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_inbox_recipient_alter_inbox_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='inbox',
            name='order',
            field=models.IntegerField(blank=True, default=0, max_length=20, null=True),
        ),
    ]
