# Generated by Django 4.0 on 2022-01-04 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_inbox_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inbox',
            name='order',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
