# Generated by Django 3.2.11 on 2023-03-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_vists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vists',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
