# Generated by Django 3.2.11 on 2023-03-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_vists_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='vists',
            name='city',
            field=models.CharField(default='NA', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='vists',
            name='country',
            field=models.CharField(default='NA', max_length=150, null=True),
        ),
    ]
