# Generated by Django 3.2.11 on 2022-01-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inboxnotif',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='inboxnotif',
            name='message_url',
        ),
        migrations.AddField(
            model_name='inboxnotif',
            name='message_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
