# Generated by Django 3.2.11 on 2022-01-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notifs', '0002_auto_20220114_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboxnotif',
            name='notif_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
