# Generated by Django 3.2.11 on 2022-12-31 10:43

import Teachers.formatChecker
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('Balance', models.FloatField(blank=True, default=0.0)),
                ('docfile', Teachers.formatChecker.ContentTypeRestrictedFileField(upload_to='cvs')),
                ('Experience', models.TextField(blank=True, max_length=500)),
                ('qualifications1', models.CharField(max_length=20)),
                ('qualifications2', models.CharField(blank=True, max_length=20)),
                ('qualifications3', models.CharField(blank=True, max_length=20)),
                ('qualifications4', models.CharField(blank=True, max_length=20)),
                ('IBAN', models.CharField(blank=True, max_length=23)),
                ('BankName', models.CharField(blank=True, max_length=30)),
                ('BankCountry', models.CharField(blank=True, max_length=30)),
                ('specialzed_courses1', models.CharField(max_length=20)),
                ('specialzed_courses2', models.CharField(blank=True, max_length=20)),
                ('specialzed_courses3', models.CharField(blank=True, max_length=20)),
                ('grades', models.CharField(blank=True, max_length=30)),
                ('Notes', models.TextField(blank=True, max_length=100)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_Regicted', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='paid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recived', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teachers.teacherprofile')),
            ],
        ),
    ]
