# Generated by Django 4.0 on 2021-12-29 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0007_ratingreview'),
        ('orders', '0027_complains'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=20)),
                ('Balance', models.FloatField(blank=True, default=0.0)),
                ('docfile', models.FileField(blank=True, upload_to='cvs')),
                ('Experience', models.TextField(blank=True, max_length=500)),
                ('qualifications1', models.CharField(blank=True, max_length=20)),
                ('qualifications2', models.CharField(blank=True, max_length=20)),
                ('qualifications3', models.CharField(blank=True, max_length=20)),
                ('qualifications4', models.CharField(blank=True, max_length=20)),
                ('Course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('orders', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orderpoduct')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
