# Generated by Django 4.0 on 2021-12-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='BankCountry',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='BankName',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='IBAN',
            field=models.CharField(blank=True, max_length=23),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
