# Generated by Django 4.0 on 2021-12-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0002_teacherprofile_bankcountry_teacherprofile_bankname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='specialzed_courses1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='specialzed_courses2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='specialzed_courses3',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
