# Generated by Django 4.0 on 2021-12-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0003_teacherprofile_specialzed_courses1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='Notes',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
