# Generated by Django 4.0 on 2021-12-29 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0004_teacherprofile_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='country',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='qualifications1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='specialzed_courses1',
            field=models.CharField(max_length=20),
        ),
    ]
