# Generated by Django 4.0 on 2021-12-29 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0005_alter_teacherprofile_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='docfile',
            field=models.FileField(upload_to='cvs'),
        ),
    ]
