# Generated by Django 4.0 on 2021-12-30 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0007_teacherprofile_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='is_Regicted',
            field=models.BooleanField(default=False),
        ),
    ]
