# Generated by Django 4.0 on 2021-12-30 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0008_teacherprofile_is_regicted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='orders',
        ),
    ]
