# Generated by Django 4.0 on 2021-12-30 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0009_remove_teacherprofile_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='Course',
        ),
    ]
