# Generated by Django 4.0 on 2021-12-31 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0010_remove_teacherprofile_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='paid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recived', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Teachers.teacherprofile')),
            ],
        ),
    ]
