# Generated by Django 4.0 on 2021-12-31 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0011_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paid',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teachers.teacherprofile'),
        ),
    ]
