# Generated by Django 3.2.11 on 2022-02-04 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closelive',
            name='is_open',
        ),
        migrations.RemoveField(
            model_name='closelive',
            name='updated_at',
        ),
    ]
