# Generated by Django 3.2.11 on 2023-02-06 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='closelive',
            name='classno',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
