# Generated by Django 3.2.11 on 2023-02-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0002_closelive_classno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closelive',
            name='order',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
