# Generated by Django 3.2.11 on 2022-02-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0003_alter_closelive_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closelive',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
