# Generated by Django 3.2.11 on 2023-02-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0003_alter_closelive_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closelive',
            name='order',
            field=models.IntegerField(unique=True),
        ),
    ]
