# Generated by Django 3.2.11 on 2022-02-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0004_alter_closelive_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closelive',
            name='order',
            field=models.CharField(max_length=1000),
        ),
    ]
