# Generated by Django 3.2.11 on 2023-02-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0004_alter_closelive_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closelive',
            name='order',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
