# Generated by Django 3.2.11 on 2023-02-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0005_alter_closelive_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closelive',
            name='classno',
            field=models.IntegerField(max_length=100),
        ),
    ]
