# Generated by Django 4.0 on 2021-12-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('grade', models.CharField(max_length=50)),
                ('language', models.CharField(choices=[('Arabic', 'Arabic'), ('English', 'English'), ('French', 'French'), ('Chinese', 'Chinese')], max_length=15)),
                ('teacher', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('img', models.ImageField(blank=True, upload_to='img/courses')),
                ('notes', models.TextField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
