# Generated by Django 4.0 on 2021-12-13 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
    ]
