# Generated by Django 3.2.11 on 2023-01-05 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20230105_0516'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tybe_Type_ar', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TypeEN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tybe_Type_en', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='type',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
        migrations.AddField(
            model_name='course',
            name='typeAR',
            field=models.ManyToManyField(blank=True, to='courses.TypeAR'),
        ),
        migrations.AddField(
            model_name='course',
            name='typeEN',
            field=models.ManyToManyField(blank=True, to='courses.TypeEN'),
        ),
    ]
