# Generated by Django 4.0 on 2021-12-13 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_notes_remove_course_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='grade',
        ),
    ]
