# Generated by Django 3.2.11 on 2023-01-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20230105_0550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursePrev1', models.CharField(blank=True, max_length=100)),
                ('coursePrev2', models.CharField(blank=True, max_length=100)),
                ('coursePrev3', models.CharField(blank=True, max_length=100)),
                ('coursePrev4', models.CharField(blank=True, max_length=100)),
                ('coursePrev5', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
