# Generated by Django 3.2.11 on 2023-01-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='coursePrevAR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priv_ar', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='coursePrevEN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priv_en', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='price',
            name='coursePrev1',
        ),
        migrations.RemoveField(
            model_name='price',
            name='coursePrev2',
        ),
        migrations.RemoveField(
            model_name='price',
            name='coursePrev3',
        ),
        migrations.RemoveField(
            model_name='price',
            name='coursePrev4',
        ),
        migrations.RemoveField(
            model_name='price',
            name='coursePrev5',
        ),
        migrations.AddField(
            model_name='price',
            name='typeAR',
            field=models.ManyToManyField(blank=True, to='courses.coursePrevAR'),
        ),
        migrations.AddField(
            model_name='price',
            name='typeEN',
            field=models.ManyToManyField(blank=True, to='courses.coursePrevEN'),
        ),
    ]
