# Generated by Django 4.0 on 2021-12-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_course_language_course_language1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_school_subject',
            field=models.BooleanField(default=True),
        ),
    ]
