# Generated by Django 3.2.11 on 2023-01-16 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20230117_0054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='typeAR',
            new_name='privAR',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='typeEN',
            new_name='privEN',
        ),
    ]
