# Generated by Django 4.0 on 2021-12-30 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0010_remove_teacherprofile_course'),
        ('courses', '0007_ratingreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Teachers.teacherprofile'),
        ),
    ]
