# Generated by Django 3.2.11 on 2023-01-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20230117_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='courseClasses',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='price',
            name='coursePrice',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='price',
            name='privAR',
            field=models.ManyToManyField(blank=True, to='courses.CoursePrevAR'),
        ),
        migrations.AlterField(
            model_name='price',
            name='privEN',
            field=models.ManyToManyField(blank=True, to='courses.CoursePrevEN'),
        ),
    ]
