# Generated by Django 3.2.11 on 2023-01-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20230117_0113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseprevar',
            old_name='priv_ar',
            new_name='privAr',
        ),
        migrations.RenameField(
            model_name='coursepreven',
            old_name='priv_en',
            new_name='privEn',
        ),
        migrations.AlterField(
            model_name='price',
            name='privAR',
            field=models.ManyToManyField(blank=True, to='courses.CoursePrevAR'),
        ),
        migrations.AlterField(
            model_name='price',
            name='privEN',
            field=models.ManyToManyField(blank=True, to='courses.CoursePrevEN'),
        ),
    ]
