# Generated by Django 3.2.11 on 2022-01-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20220119_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_name_en',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='course',
            name='language1_ar',
        ),
        migrations.RemoveField(
            model_name='course',
            name='language1_en',
        ),
        migrations.RemoveField(
            model_name='course',
            name='language2_ar',
        ),
        migrations.RemoveField(
            model_name='course',
            name='language2_en',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name_ar',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
