# Generated by Django 3.2.11 on 2023-01-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20230117_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='courseClasses_Ar',
            field=models.CharField(default='واحد', max_length=30),
        ),
        migrations.AddField(
            model_name='price',
            name='courseClasses_En',
            field=models.CharField(default='one', max_length=30),
        ),
        migrations.AlterField(
            model_name='price',
            name='privAR',
            field=models.ManyToManyField(blank=True, to='courses.CoursePrevAR'),
        ),
        migrations.AlterField(
            model_name='price',
            name='privEN',
            field=models.ManyToManyField(blank=True, to='courses.CoursePrevEN'),
        ),
    ]
