# Generated by Django 3.2.11 on 2022-01-19 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0012_alter_paid_teacher'),
        ('courses', '0010_auto_20220120_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Teachers.teacherprofile'),
        ),
    ]
