# Generated by Django 3.2.11 on 2023-02-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0038_auto_20230211_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='country',
            field=models.CharField(blank=True, choices=[('UAE', 'الإمارات'), ('KSA', 'السعودية'), ('Qatar', 'قطر'), ('Kuwait', 'الكويت'), ('Egypt', 'مصر')], max_length=30),
        ),
        migrations.AlterField(
            model_name='price',
            name='CprivAR',
            field=models.ManyToManyField(blank=True, to='courses.CoursePrevAR'),
        ),
        migrations.AlterField(
            model_name='price',
            name='CprivEN',
            field=models.ManyToManyField(blank=True, to='courses.CoursePrevEN'),
        ),
    ]
