# Generated by Django 3.2.11 on 2023-02-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_trial',
            field=models.BooleanField(default=False),
        ),
    ]
