# Generated by Django 3.2.11 on 2023-02-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_is_trial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpoductclasses',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
