# Generated by Django 4.0 on 2021-12-15 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpoduct',
            name='class_material_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='orderpoduct',
            name='class_url',
            field=models.URLField(blank=True),
        ),
    ]
