# Generated by Django 4.0 on 2021-12-16 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_is_school_subject'),
        ('orders', '0004_orderpoduct_class_material_url_orderpoduct_class_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
