# Generated by Django 4.0 on 2021-12-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_order_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gtotal',
            field=models.FloatField(default=0.0),
        ),
    ]
