# Generated by Django 3.2.11 on 2023-02-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20230211_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeteacherrequestt',
            name='type',
            field=models.CharField(blank=True, default='other', max_length=100),
        ),
    ]
