# Generated by Django 3.2.11 on 2023-02-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_changeteacherrequestt_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeteacherrequestt',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
