# Generated by Django 4.0 on 2021-12-19 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_gtotal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpoduct',
            name='classes',
        ),
        migrations.AddField(
            model_name='order',
            name='total_classes',
            field=models.IntegerField(default=1),
        ),
    ]
