# Generated by Django 4.0 on 2021-12-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_orderpoduct_classes_order_total_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_classes',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
