# Generated by Django 4.0 on 2021-12-21 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_course_language',
            field=models.CharField(blank=True, default='Arabic', max_length=20),
        ),
    ]
