# Generated by Django 4.0 on 2021-12-22 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='grade',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
