# Generated by Django 4.0 on 2021-12-23 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpoduct',
            name='class_url',
        ),
        migrations.AddField(
            model_name='orderpoduct',
            name='is_deliverd',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='orderPoductClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_url', models.URLField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
