# Generated by Django 4.0 on 2021-12-26 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpoductclasses',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderpoductclasses',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
