# Generated by Django 4.0 on 2021-12-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_orderpoductclasses_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpoductclasses',
            name='class_url_is_deliverd',
            field=models.BooleanField(default=False),
        ),
    ]
