# Generated by Django 4.0 on 2021-12-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_is_school_subject'),
        ('orders', '0021_connect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connect',
            name='Course',
        ),
        migrations.AddField(
            model_name='connect',
            name='Course',
            field=models.ManyToManyField(to='courses.course'),
        ),
        migrations.RemoveField(
            model_name='connect',
            name='orderd',
        ),
        migrations.AddField(
            model_name='connect',
            name='orderd',
            field=models.ManyToManyField(to='orders.orderPoduct'),
        ),
    ]
