# Generated by Django 4.0 on 2021-12-29 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_connector_delete_connect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingreview',
            name='course',
        ),
        migrations.RemoveField(
            model_name='ratingreview',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ratingreview',
            name='user',
        ),
        migrations.DeleteModel(
            name='connector',
        ),
        migrations.DeleteModel(
            name='RatingReview',
        ),
    ]
