# Generated by Django 4.0 on 2021-12-29 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_changeteacherrequestt'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeteacherrequestt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='changeteacherrequestt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
